[2018-01-05 03:31:52] 2018-01-05 03:31:52 exception 'PDOException' with message 'SQLSTATE[08006] [7] could not translate host name "localhost1" to address: nodename nor servname provided, or not known' in /data1/work/zf/store/app/config/services.php:86
Stack trace:
#0 [internal function]: PDO->__construct('pgsql:host=loca...', 'postgres', '123456', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\Postgresql->connect(Array)
#3 /data1/work/zf/store/app/config/services.php(86): Phalcon\Db\Adapter\Pdo->__construct(Array)
#4 [internal function]: Closure->{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('db', NULL)
#7 [internal function]: Phalcon\Di->getShared('db')
#8 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(app\models\Users), NULL)
#9 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(app\models\Users))
#10 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#11 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(app\models\Users), Object(Phalcon\Di\FactoryDefault))
#12 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(app\models\Users), 'app\\models\\user...', 'users', '')
#13 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaDataIndex(Object(app\models\Users), 1)
#14 [internal function]: Phalcon\Mvc\Model\MetaData->getPrimaryKeyAttributes(Object(app\models\Users))
#15 [internal function]: Phalcon\Mvc\Model\Query\Builder->getPhql()
#16 [internal function]: Phalcon\Mvc\Model\Query\Builder->getQuery()
#17 /data1/work/zf/store/app/controllers/TestController.php(121): Phalcon\Mvc\Model::findFirst(3)
#18 [internal function]: app\controllers\TestController->t2Action()
#19 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(app\controllers\TestController), 't2Action', Array)
#20 [internal function]: Phalcon\Dispatcher->dispatch()
#21 /data1/work/zf/store/public/index.php(104): Phalcon\Mvc\Application->handle()
#22 {main}
[2018-01-05 03:35:07] 2018-01-05 03:35:07 exception 'PDOException' with message 'SQLSTATE[08006] [7] could not translate host name "localhost1" to address: nodename nor servname provided, or not known' in /data1/work/zf/store/app/config/services.php:86
Stack trace:
#0 [internal function]: PDO->__construct('pgsql:host=loca...', 'postgres', '123456', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\Postgresql->connect(Array)
#3 /data1/work/zf/store/app/config/services.php(86): Phalcon\Db\Adapter\Pdo->__construct(Array)
#4 [internal function]: Closure->{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('db', NULL)
#7 [internal function]: Phalcon\Di->getShared('db')
#8 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(app\models\Users), NULL)
#9 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(app\models\Users))
#10 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#11 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(app\models\Users), Object(Phalcon\Di\FactoryDefault))
#12 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(app\models\Users), 'app\\models\\user...', 'users', '')
#13 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaDataIndex(Object(app\models\Users), 1)
#14 [internal function]: Phalcon\Mvc\Model\MetaData->getPrimaryKeyAttributes(Object(app\models\Users))
#15 [internal function]: Phalcon\Mvc\Model\Query\Builder->getPhql()
#16 [internal function]: Phalcon\Mvc\Model\Query\Builder->getQuery()
#17 /data1/work/zf/store/app/controllers/TestController.php(121): Phalcon\Mvc\Model::findFirst(3)
#18 [internal function]: app\controllers\TestController->t2Action()
#19 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(app\controllers\TestController), 't2Action', Array)
#20 [internal function]: Phalcon\Dispatcher->dispatch()
#21 /data1/work/zf/store/public/index.php(104): Phalcon\Mvc\Application->handle()
#22 {main}
[2018-01-05 03:36:19] 2018-01-05 03:36:19 exception 'PDOException' with message 'SQLSTATE[08006] [7] could not translate host name "localhost1" to address: nodename nor servname provided, or not known' in /data1/work/zf/store/app/config/services.php:86
Stack trace:
#0 [internal function]: PDO->__construct('pgsql:host=loca...', 'postgres', '123456', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\Postgresql->connect(Array)
#3 /data1/work/zf/store/app/config/services.php(86): Phalcon\Db\Adapter\Pdo->__construct(Array)
#4 [internal function]: Closure->{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('db', NULL)
#7 [internal function]: Phalcon\Di->getShared('db')
#8 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(app\models\Users), NULL)
#9 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(app\models\Users))
#10 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#11 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(app\models\Users), Object(Phalcon\Di\FactoryDefault))
#12 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(app\models\Users), 'app\\models\\user...', 'users', '')
#13 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaDataIndex(Object(app\models\Users), 1)
#14 [internal function]: Phalcon\Mvc\Model\MetaData->getPrimaryKeyAttributes(Object(app\models\Users))
#15 [internal function]: Phalcon\Mvc\Model\Query\Builder->getPhql()
#16 [internal function]: Phalcon\Mvc\Model\Query\Builder->getQuery()
#17 /data1/work/zf/store/app/controllers/TestController.php(121): Phalcon\Mvc\Model::findFirst(3)
#18 [internal function]: app\controllers\TestController->t2Action()
#19 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(app\controllers\TestController), 't2Action', Array)
#20 [internal function]: Phalcon\Dispatcher->dispatch()
#21 /data1/work/zf/store/public/index.php(104): Phalcon\Mvc\Application->handle()
#22 {main}
[2018-01-05 03:40:50] 2018-01-05 03:40:50 exception 'PDOException' with message 'SQLSTATE[08006] [7] could not translate host name "localhost1" to address: nodename nor servname provided, or not known' in /data1/work/zf/store/app/config/services.php:86
Stack trace:
#0 [internal function]: PDO->__construct('pgsql:host=loca...', 'postgres', '123456', Array)
#1 [internal function]: Phalcon\Db\Adapter\Pdo->connect(Array)
#2 [internal function]: Phalcon\Db\Adapter\Pdo\Postgresql->connect(Array)
#3 /data1/work/zf/store/app/config/services.php(86): Phalcon\Db\Adapter\Pdo->__construct(Array)
#4 [internal function]: Closure->{closure}()
#5 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#6 [internal function]: Phalcon\Di->get('db', NULL)
#7 [internal function]: Phalcon\Di->getShared('db')
#8 [internal function]: Phalcon\Mvc\Model\Manager->_getConnection(Object(app\models\Users), NULL)
#9 [internal function]: Phalcon\Mvc\Model\Manager->getReadConnection(Object(app\models\Users))
#10 [internal function]: Phalcon\Mvc\Model->getReadConnection()
#11 [internal function]: Phalcon\Mvc\Model\MetaData\Strategy\Introspection->getMetaData(Object(app\models\Users), Object(Phalcon\Di\FactoryDefault))
#12 [internal function]: Phalcon\Mvc\Model\MetaData->_initialize(Object(app\models\Users), 'app\\models\\user...', 'users', '')
#13 [internal function]: Phalcon\Mvc\Model\MetaData->readMetaDataIndex(Object(app\models\Users), 1)
#14 [internal function]: Phalcon\Mvc\Model\MetaData->getPrimaryKeyAttributes(Object(app\models\Users))
#15 [internal function]: Phalcon\Mvc\Model\Query\Builder->getPhql()
#16 [internal function]: Phalcon\Mvc\Model\Query\Builder->getQuery()
#17 /data1/work/zf/store/app/controllers/TestController.php(121): Phalcon\Mvc\Model::findFirst(3)
#18 [internal function]: app\controllers\TestController->t2Action()
#19 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(app\controllers\TestController), 't2Action', Array)
#20 [internal function]: Phalcon\Dispatcher->dispatch()
#21 /data1/work/zf/store/public/index.php(104): Phalcon\Mvc\Application->handle()
#22 {main}
